version: '3.4'

services:
  onlineexam:
    image: onlineexam
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4300:4300
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
